# Server configuration
server.port=8501

# Spotify API Configuration
SPOTIPY_CLIENT_ID=2cefb9ee271b491aa6da1aba31f3fdd2
SPOTIPY_CLIENT_SECRET=fe418ec93b3a487ca0834304fe0c8217
SPOTIPY_REDIRECT_URI=http://127.0.0.1:8501/

# Google Gemini API Configuration (Set as environment variable)
GEMINI_API_KEY=AIzaSyDaWPJJFKTl3WG7P97pIk8qO6sVEJSk3ZM

# Increase file upload limits for Spring Boot
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
